name: Generate Snake

on:
  # Executa automaticamente a cada 6 horas
  schedule:
    - cron: "0 */6 * * *"
  # Permite executar manualmente na aba Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@v3
        with:
          # Seu usu√°rio GitHub
          github_user_name: CortesMichael
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
